development:
  adapter: postgresql
  database: giggerator_development
  host: localhost

test:
  adapter: postgresql
  database: giggerator_test
  host: localhost

production:
  adapter: postgresql
  database: giggerator_production
  host: localhost
